# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.005

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_trajectory_controller
    - right_arm_trajectory_controller
    - head_trajectory_controller
    # - left_arm_eef_controller
    # - right_arm_eef_controller

  left_arm_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
      - left_arm_joint6

  right_arm_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6

  head_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - head_yaw_joint
      - head_pitch_joint

  # left_arm_eef_controller:
  #   type: GripperCommand
  #   joints:
  #     - left_arm_eef_gripper_joint
  #   action_ns: gripper_cmd
  #   default: true

  # right_arm_eef_controller:
  #   type: GripperCommand
  #   joints:
  #     - right_arm_eef_gripper_joint
  #   action_ns: gripper_cmd
  #   default: true
