# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.25
default_acceleration_scaling_factor: 0.25

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_arm_eef_gripper_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 6.28
  right_arm_eef_gripper_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 6.28
  left_arm_joint1:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 3.1415926535897931
  left_arm_joint2:
    has_velocity_limits: true
    max_velocity: 3.9269908169872414
    has_acceleration_limits: true
    max_acceleration: 3.9269908169872414
  left_arm_joint3:
    has_velocity_limits: true
    max_velocity: 4.7123889803846897
    has_acceleration_limits: true
    max_acceleration: 4.7123889803846897
  left_arm_joint4:
    has_velocity_limits: true
    max_velocity: 6.2800000000000002
    has_acceleration_limits: true
    max_acceleration: 6.2800000000000002
  left_arm_joint5:
    has_velocity_limits: true
    max_velocity: 6.2800000000000002
    has_acceleration_limits: true
    max_acceleration: 6.2800000000000002
  left_arm_joint6:
    has_velocity_limits: true
    max_velocity: 6.2800000000000002
    has_acceleration_limits: true
    max_acceleration: 6.2800000000000002
  right_arm_joint1:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 3.1415926535897931
  right_arm_joint2:
    has_velocity_limits: true
    max_velocity: 3.9269908169872414
    has_acceleration_limits: true
    max_acceleration: 3.9269908169872414
  right_arm_joint3:
    has_velocity_limits: true
    max_velocity: 4.7123889803846897
    has_acceleration_limits: true
    max_acceleration: 4.7123889803846897
  right_arm_joint4:
    has_velocity_limits: true
    max_velocity: 6.2800000000000002
    has_acceleration_limits: true
    max_acceleration: 6.2800000000000002
  right_arm_joint5:
    has_velocity_limits: true
    max_velocity: 6.2800000000000002
    has_acceleration_limits: true
    max_acceleration: 6.2800000000000002
  right_arm_joint6:
    has_velocity_limits: true
    max_velocity: 6.2800000000000002
    has_acceleration_limits: true
    max_acceleration: 6.2800000000000002
  head_yaw_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 3.1415926535897931
  head_pitch_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 3.1415926535897931
