# Default initial positions for mmk2's ros2_control fake system

initial_positions:
  left_arm_eef_gripper_joint: 0
  left_arm_joint1: 0
  left_arm_joint2: 0
  left_arm_joint3: 0
  left_arm_joint4: 0
  left_arm_joint5: 0
  left_arm_joint6: 0
  right_arm_eef_gripper_joint: 0
  right_arm_joint1: 0
  right_arm_joint2: 0
  right_arm_joint3: 0
  right_arm_joint4: 0
  right_arm_joint5: 0
  right_arm_joint6: 0
  head_yaw_joint: 0
  head_pitch_joint: 0